import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ServerNabBAr from "./ui/navabr/ServerNabBAr";
import ClientSessionProvider from "./SessionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body>
        <ClientSessionProvider>
          <ServerNabBAr /> {children}
        </ClientSessionProvider>
      </body>
    </html>
  );
}
